### ISSUE TITLE
Error when running 

### ISSUE THREAD

**Issue by soapycar45** [debaet/IXLMultiBot#5]
Everytime i run it i get the error 

"

Traceback (most recent call last):
  File "C:\Users\jamie\Desktop\IXLMultiBot-main\IXLMultiBot-main\main.py", line 18, in <module>
    driver = webdriver.Chrome(PATH)
  File "C:\Users\jamie\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 73, in __init__
    self.service.start()
  File "C:\Users\jamie\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\common\service.py", line 98, in start
    self.assert_process_still_running()
  File "C:\Users\jamie\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\common\service.py", line 109, in assert_process_still_running
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: Service C:/Program Files (x86)/Google/Chrome/Application/chrome.exe unexpectedly exited. Status code was: 0

"

![Screenshot 2021-09-19 175234](https://user-images.githubusercontent.com/67769333/133948692-668cf222-8085-4a8a-b2fe-2f42f7bf75a9.png)

**Comment by relzeor** [comment]
I can help the problem is the driver make sure your on the right version and when you put the link he have to do it like this "C:\\\Desktop\\\\\" with the 2 slashes.
